Repository capistrano/capistrano, pull requests merged in 2020-03, with the labels that each got.

#2050 Change default `git_wait_interval` to 0 to fix git slowdown introduced in 3.12.0
  docs/documentation/getting-started/configuration/index.markdown
  lib/capistrano/scm/git.rb
  spec/lib/capistrano/scm/git_spec.rb
Labels: 🐛 Bug Fix

#2052 Improve misleading example for ssh_options
  lib/capistrano/templates/stage.rb.erb
Labels: 📚 Docs

#2054 Remove CHANGELOG task from PR template
  .github/pull_request_template.md
Labels: 🏠 Housekeeping
