Repository capistrano/capistrano, pull requests merged in 2023-05, with the labels that each got.

#2128 fix typo
  docs/documentation/getting-started/authentication-and-authorisation/index.markdown
Labels: 📚 Docs

#2127 Allow legacy-v2 test suite to run locally on modern Rubies
  Gemfile
Labels: v2, 🏠 Housekeeping

#2129 Fix deprecated usage of open-uri so feature tests work on Ruby 3
  spec/support/Vagrantfile
Labels: 🏠 Housekeeping

#2132 Migrate from CircleCI to GitHub Actions; add Cucumber features to CI
  .circleci/config.yml
  .github/workflows/ci.yml
  DEVELOPMENT.md
  README.md
Labels: 🏠 Housekeeping
